name: CI

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  
jobs:
  build:  
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Run Makefile
        run: |
          make run 

      - name: Configure Git
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"

      - name: Checkout repository and switch to target branch
        run: |
          file_path="data/raw/extract_$(date +%Y-%m-%d).jsonl"
          if [ -f "$file_path" ]; then
            git add data/raw
            git commit -m "add generated files from data folder on $(date +%Y-%m-%d)"
            git switch --orphan data_raw
            git checkout  develop -- data/raw
            git commit -m "task: fetched data for $(date +%Y-%m-%d)"
            git push origin HEAD:data_raw
          else
            echo "File $file_path does not exist."
          fi