name: CI

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  
jobs:
  build:  
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Run Makefile
        run: |
          make run 
      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Checkout repository and switch to target branch
        run: |
          git checkout -b data_raw

      - name: Remove all existing files except data folder
        run: |
          shopt -s extglob
          rm -rf !(data)
          shopt -u extglob
      - name: Commit and push data folder changes to another branch
        run: |
          file_path="data/raw/extract_$(date +%Y-%m-%d).jsonl"
          # Check if the file exists
          if [ -f "$file_path" ]; then
            # Add the file to the staging area
            git add "$file_path"
          
            # Commit the changes with an appropriate message
            git commit -m "Add generated file generated on $(date +%Y-%m-%d)"
            git push origin HEAD:data_raw
          else
            echo "File $file_pat
