name: extract_news

on:
  push:
    branches: [develop]
  #schedule:
   # - cron: '0 */6 * * *'

permissions:
  contents: write
  
jobs:
  build:  
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Run Makefile
        run: |
          make run 

      - name: Checkout repository and switch to target branch
        run: |
          git config  user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config  user.name "$(gh api /users/${GITHUB_ACTOR} | jq .name -r)"
          file_path="data/raw/extract_$(date +%Y-%m-%d_%H).jsonl"
          if [ -f "$file_path" ]; then
            git add data/raw
            git commit -m "add generated files from data folder on $(date +%Y-%m-%d_%H)"
            git switch --orphan data_raw
            git checkout  develop -- data/raw
            git commit -m "task: fetched data for $(date +%Y-%m-%d_%H) at ${H}"
            git push origin HEAD:data_raw
          else
            echo "File $file_path does not exist."
          fi